[package]
name = "pta-template-engine"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ptatemp"
path = "src/main.rs"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.19", features = ["derive"] }
minijinja = { version = "2.3.1", features = ["builtins"] }
regex = "1.11.0"
